import turtle
wd=turtle.Screen()
wd.bgcolor("black")
t=turtle.Turtle()
t.speed(1)
t.shape("turtle")

t.up()
t.setheading(270)
t.forward(100)
t.setheading(0)
t.down()
t.color("Red")
t.begin_fill()
t.fillcolor("Red")
t.left(140)
t.forward(180)
t.circle(-90,extent=200)
t.setheading(60)
t.circle(-90,extent=200)
t.forward(180)
t.end_fill()
t.hideturtle()
turtle.done()