import turtle
t=turtle.Turtle()
t.speed(3)
t.begin_fill()
t.fillcolor("red")
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.end_fill()
t.hideturtle()
t.back(200)
t.speed(10)
t.begin_fill()
t.fillcolor("green")
for i in range(4):
    t.fd(100)
    t.left(90)
t.end_fill()
turtle.done()